//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FILETEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILESAVETEST
    {
        public int IDX { get; set; }
        public Nullable<int> FILE_SIZE { get; set; }
        public string FILE_EXTENTION { get; set; }
        public string FILE_ORGNAME { get; set; }
        public string FILE_ENCODINGNAME { get; set; }
        public Nullable<System.DateTime> FILE_SAVEDATE { get; set; }
        public Nullable<System.DateTime> REGDATE { get; set; }
        public string REGID { get; set; }
        public Nullable<System.DateTime> UPDDATE { get; set; }
        public string UPDID { get; set; }
        public string ISUSE { get; set; }
        public string ETC { get; set; }
    }
}
